### ISSUE TITLE
Cannot send raw transaction

### ISSUE THREAD

**Issue by daichuanliang** [ericlee42/metis-replica-node-guide#1]
I have set up a Metis node and  synced the latest block through the guide. But I cannot send any transaction.

Log:  l2geth_1  | WARN [02-10|04:11:46.964] Served eth_sendRawTransaction            conn=192.168.224.1:50302 reqid=8511548653344 t=25.198µs  err="Cannot send raw transaction in verifier mode"

**Comment by ericlee42** [comment]
![Screen Shot 2022-02-10 at 12 14 29 PM](https://user-images.githubusercontent.com/92196970/153336019-fc0d3b08-ab81-4979-afd0-0a6d87f4c770.png)

**Comment by daichuanliang** [comment]
So, if I wan't to submmit my txs without public rpc node, how should I do?(I mean use my rpc node, do you have any guide to set up Metis full node?)

**Comment by daichuanliang** [comment]
So, if I want to submmit my txs without public rpc node, how should I do?(I mean use my rpc node, do you have any guide to set up Metis full node?)

**Comment by ericlee42** [comment]
There is no such node role
