### ISSUE TITLE
mvm version in docker

### ISSUE THREAD

**Issue by macrocan** [ericlee42/metis-replica-node-guide#11]
Hey, guys，I am wondering what mvm's version / commit id in the 'metisdao/mvm-andromeda'.
Is it  corresponds to andromeda branch in mvm github repo？

As l2geth is last updated 5 months ago, but docker image is updated 8 days ago, So I am puzzled.

**Comment by ericlee42** [comment]
check out docker hub https://hub.docker.com/r/metisdao/mvm-andromeda/tags
