### ISSUE TITLE
Change docker image tags

### ISSUE THREAD

**Issue by vlads123** [ericlee42/metis-replica-node-guide#13]
I think you're using docker tags in a bad way.

The main issue for me is, if you have docker tags like :dtl, :l2geth - then you never know what is the version will be run, similar to :latest. 

So to have a static environment, I(and everyone who needs a stable/static environment) have to pull the images, re-tag them with the proper version (I'm using the application version as the tag) and then pull them to my repo.

Please see best practices here https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-tag-version

Or just check how alpine Linux tags are set up.

Please lmk if any other questions

**Comment by ericlee42** [comment]
Thank you for your suggestion. 

We will add image tag in the next version.
