### ISSUE TITLE
unable to start up l2geth 

### ISSUE THREAD

**Issue by punk5558** [ericlee42/metis-replica-node-guide#14]
Hello, 

I followed your set up instructions and dtl is running fine. However, after I run the docker-compose command on l2geth, it went through the pulling/ downloading and ended with l2geth creating, created, starting, started. But when I run the following, there is no data. Appreciate your assistance! 

$ docker-compose logs --tail=10 l2geth
metis-replica-node-guide-l2geth-1  | monitor         off
metis-replica-node-guide-l2geth-1  | noexec          off
metis-replica-node-guide-l2geth-1  | xtrace          off
metis-replica-node-guide-l2geth-1  | verbose         off
metis-replica-node-guide-l2geth-1  | noclobber       off
metis-replica-node-guide-l2geth-1  | allexport       off
metis-replica-node-guide-l2geth-1  | notify          off
metis-replica-node-guide-l2geth-1  | nounset         off
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off

**Comment by ericlee42** [comment]
there are too few logs for me to help

**Comment by punk5558** [comment]
please take a look at this 

$ docker-compose logs --tail=100 l2geth
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off
metis-replica-node-guide-l2geth-1  | errexit         on
metis-replica-node-guide-l2geth-1  | ./geth.sh: set: line 2: illegal option -
metis-replica-node-guide-l2geth-1  | noglob          off
metis-replica-node-guide-l2geth-1  | ignoreeof       off
metis-replica-node-guide-l2geth-1  | monitor         off
metis-replica-node-guide-l2geth-1  | noexec          off
metis-replica-node-guide-l2geth-1  | xtrace          off
metis-replica-node-guide-l2geth-1  | verbose         off
metis-replica-node-guide-l2geth-1  | noclobber       off
metis-replica-node-guide-l2geth-1  | allexport       off
metis-replica-node-guide-l2geth-1  | notify          off
metis-replica-node-guide-l2geth-1  | nounset         off
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off
metis-replica-node-guide-l2geth-1  | ./geth.sh: set: line 2: illegal option -
metis-replica-node-guide-l2geth-1  | errexit         on
metis-replica-node-guide-l2geth-1  | noglob          off
metis-replica-node-guide-l2geth-1  | ignoreeof       off
metis-replica-node-guide-l2geth-1  | monitor         off
metis-replica-node-guide-l2geth-1  | noexec          off
metis-replica-node-guide-l2geth-1  | xtrace          off
metis-replica-node-guide-l2geth-1  | verbose         off
metis-replica-node-guide-l2geth-1  | noclobber       off
metis-replica-node-guide-l2geth-1  | allexport       off
metis-replica-node-guide-l2geth-1  | notify          off
metis-replica-node-guide-l2geth-1  | nounset         off
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off
metis-replica-node-guide-l2geth-1  | ./geth.sh: set: line 2: illegal option -
metis-replica-node-guide-l2geth-1  | errexit         on
metis-replica-node-guide-l2geth-1  | noglob          off
metis-replica-node-guide-l2geth-1  | ignoreeof       off
metis-replica-node-guide-l2geth-1  | monitor         off
metis-replica-node-guide-l2geth-1  | noexec          off
metis-replica-node-guide-l2geth-1  | xtrace          off
metis-replica-node-guide-l2geth-1  | verbose         off
metis-replica-node-guide-l2geth-1  | noclobber       off
metis-replica-node-guide-l2geth-1  | allexport       off
metis-replica-node-guide-l2geth-1  | notify          off
metis-replica-node-guide-l2geth-1  | nounset         off
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off
metis-replica-node-guide-l2geth-1  | ./geth.sh: set: line 2: illegal option -
metis-replica-node-guide-l2geth-1  | errexit         on
metis-replica-node-guide-l2geth-1  | noglob          off
metis-replica-node-guide-l2geth-1  | ignoreeof       off
metis-replica-node-guide-l2geth-1  | monitor         off
metis-replica-node-guide-l2geth-1  | noexec          off
metis-replica-node-guide-l2geth-1  | xtrace          off
metis-replica-node-guide-l2geth-1  | verbose         off
metis-replica-node-guide-l2geth-1  | noclobber       off
metis-replica-node-guide-l2geth-1  | allexport       off
metis-replica-node-guide-l2geth-1  | notify          off
metis-replica-node-guide-l2geth-1  | nounset         off
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off
metis-replica-node-guide-l2geth-1  | ./geth.sh: set: line 2: illegal option -
metis-replica-node-guide-l2geth-1  | errexit         on
metis-replica-node-guide-l2geth-1  | noglob          off
metis-replica-node-guide-l2geth-1  | ignoreeof       off
metis-replica-node-guide-l2geth-1  | monitor         off
metis-replica-node-guide-l2geth-1  | noexec          off
metis-replica-node-guide-l2geth-1  | xtrace          off
metis-replica-node-guide-l2geth-1  | verbose         off
metis-replica-node-guide-l2geth-1  | noclobber       off
metis-replica-node-guide-l2geth-1  | allexport       off
metis-replica-node-guide-l2geth-1  | notify          off
metis-replica-node-guide-l2geth-1  | nounset         off
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off
metis-replica-node-guide-l2geth-1  | errexit         on
metis-replica-node-guide-l2geth-1  | noglob          off
metis-replica-node-guide-l2geth-1  | ignoreeof       off
metis-replica-node-guide-l2geth-1  | monitor         off
metis-replica-node-guide-l2geth-1  | noexec          off
metis-replica-node-guide-l2geth-1  | xtrace          off
metis-replica-node-guide-l2geth-1  | verbose         off
metis-replica-node-guide-l2geth-1  | noclobber       off
metis-replica-node-guide-l2geth-1  | allexport       off
metis-replica-node-guide-l2geth-1  | notify          off
metis-replica-node-guide-l2geth-1  | nounset         off
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off
metis-replica-node-guide-l2geth-1  | ./geth.sh: set: line 2: illegal option -
metis-replica-node-guide-l2geth-1  | ./geth.sh: set: line 2: illegal option -
metis-replica-node-guide-l2geth-1  | errexit         on
metis-replica-node-guide-l2geth-1  | noglob          off
metis-replica-node-guide-l2geth-1  | ignoreeof       off
metis-replica-node-guide-l2geth-1  | monitor         off
metis-replica-node-guide-l2geth-1  | noexec          off
metis-replica-node-guide-l2geth-1  | xtrace          off
metis-replica-node-guide-l2geth-1  | verbose         off
metis-replica-node-guide-l2geth-1  | noclobber       off
metis-replica-node-guide-l2geth-1  | allexport       off
metis-replica-node-guide-l2geth-1  | notify          off
metis-replica-node-guide-l2geth-1  | nounset         off
metis-replica-node-guide-l2geth-1  | vi              off
metis-replica-node-guide-l2geth-1  | pipefail        off

**Comment by ericlee42** [comment]
Works for me, you should read the README.md and check your config again

<img width="737" alt="Screen Shot 2022-08-05 at 13 34 09" src="https://user-images.githubusercontent.com/92196970/183008475-931e9fe7-9ee8-48aa-9429-80d77c91e49d.png">

**Comment by punk5558** [comment]
not sure if it is issue with docker, if you could point me in the right direction, that will be great! thanks! 

![space issue](https://user-images.githubusercontent.com/105208421/183017691-c6cd4145-ae80-4ce3-8509-9bec8cb5f190.png)

**Comment by ericlee42** [comment]
You should use linux.

**Comment by ericlee42** [comment]
I'm going to close this issue, please feel free to open it again
