### ISSUE TITLE
Fatal: Error starting protocol stack: Cannot initialize syncservice: 

### ISSUE THREAD

**Issue by dineshtiwari69** [ericlee42/metis-replica-node-guide#7]
I was trying to setup the node but encountered this error . Can u please tell me what went wrong?

Fatal: Error starting protocol stack: Cannot initialize syncservice: Cannot initialize latest L1 data: Must configure with canonical transaction chain deploy height

**Comment by ericlee42** [comment]
it's fixed now

**Comment by dineshtiwari69** [comment]
Thanks it was working for a while and then i started getting this error on rpc .
What does this mean and whats the potential fix ?

ValueError: {'code': 0, 'message': 'Post "http://l2geth:8545": context deadline exceeded'}

**Comment by ericlee42** [comment]
default timeout is 5 seconds

**Comment by ericlee42** [comment]
check out https://github.com/ericlee42/metis-replica-node-guide/blob/main/docker-compose-mainnet.yml#L67-L68
