### ISSUE TITLE
Public Rpc websocket is not working

### ISSUE THREAD

**Issue by abhishekhg** [ericlee42/metis-replica-node-guide#9]
Public WebSocket is not getting connected please look into the issue

**Comment by ericlee42** [comment]
It works for me
<img width="574" alt="Screen Shot 2022-04-05 at 13 19 38" src="https://user-images.githubusercontent.com/92196970/161684129-4a5f095d-a70b-460b-be98-4d98d821cd22.png">
<img width="719" alt="Screen Shot 2022-04-05 at 13 20 12" src="https://user-images.githubusercontent.com/92196970/161684143-e196204e-1dde-456e-9bf2-9b04c4d2a6bd.png">

**Comment by abhishekhg** [comment]
It doesn't connect all the time most of the time its panicking
